### PR TITLE
Lowercase storage acct name

### PR DESCRIPTION
**Pull request by danmelamed**
force storage account name to lowercase; otherwise deployment fails

### CODE REVIEW

**Comment by eisber** [comment]
I’m actually voting for random storage name using uniqueId and seeded with the subscription id + resource group name.
What do you think?

**Comment by lhoang29** [comment]
is there no lowercase function?

**Comment by danmelamed** [comment]
Yes, that’s exactly what I used to fix it.

**Comment by danmelamed** [comment]
That would kill 2 birds with one stone, so I’m in favor.

Dan

**Comment by danmelamed** [comment]
Just checked and uniqueID is not random; it’s a deterministic hash.  So it would give us only security through obscurity.  I remember reading that there is no way to get ARM to generate a random string, so I say we just lowercase it for now.

Dan

From: Dan Melamed
Sent: Friday, June 10, 2016 5:47 PM
To: 'multiworldtesting/ds-provisioning' <reply@reply.github.com>; multiworldtesting/ds-provisioning <ds-provisioning@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [multiworldtesting/ds-provisioning] Lowercase storage acct name (#1)

That would kill 2 birds with one stone, so I’m in favor.

Dan

**Comment by eisber** [comment]
There's some fun way of doing things in arm. We can seed the hash using the generated storage key ?.
As for the storage name my original intent was to make it easier to choose a valid resource name.

Markus

On Jun 10, 2016, at 8:57 PM, Dan M <notifications@github.com<mailto:notifications@github.com>> wrote:

Just checked and uniqueID is not random; it's a deterministic hash. So it would give us only security through obscurity. I remember reading that there is no way to get ARM to generate a random string, so I say we just lowercase it for now.

Dan

From: Dan Melamed
Sent: Friday, June 10, 2016 5:47 PM
To: 'multiworldtesting/ds-provisioning' <reply@reply.github.com<mailto:reply@reply.github.com>>; multiworldtesting/ds-provisioning <ds-provisioning@noreply.github.com<mailto:ds-provisioning@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [multiworldtesting/ds-provisioning] Lowercase storage acct name (#1)

That would kill 2 birds with one stone, so I'm in favor.

Dan

**Comment by danmelamed** [comment]
Is it possible to generate the key before generating the storage account?

**Comment by eisber** [comment]
Oh I see. So the schema using the storage key as seed is good for generation of the admin token or user token. As for the storage account name we don’t need something truly random, just something unique. So hashing the resource group name is probably good enough…

**Comment by lhoang29** [comment]
although with the current setup the storage account should also be unique given that the resource group is unique (which is required), right?

**Comment by eisber** [comment]
The resource group needs to be unique globally or just within the subscription?
Anyway the weird name limitation of the storage account name is currently bubbling up…

**Comment by danmelamed** [comment]
RG names can be duplicate across subscriptions (I just created such to verity).  Hashing it won’t make it unique.

**Comment by eisber** [comment]
True. So let’s mix in the subscription and maybe tenant id. That should do it?

**Comment by lhoang29** [comment]
that's weird, I thought uniqueString is supposed to give you unique resource name, but maybe only within a subscription. 

(p/s: replying via email is blowing up github conversation thread :))

**Comment by danmelamed** [comment]
Unfortunately, it can be max only 24 chars.

**Comment by eisber** [comment]
Mixing into the seed, not the name. Dan is right, unqieString just hashes.

**Comment by lhoang29** [comment]
Going to merge this one in, but will add more changes afterwards as discussed offline. We can seed uniqueString() with tenant id, sub id, and rg name. The resulting name will be prefixed with storage for discoverability. Other resources which require globally unique names will follow similar scheme

**Pull request merged**
